package github

import (
	"context"
	"fmt"

	gh "github.com/google/go-github/v66/github"
	"github.com/jakkayy/kuberlauncher/api/internal/generator"
	"golang.org/x/oauth2"
)

type Client struct {
	gh    *gh.Client
	owner string
}

func New(token, owner string) *Client {
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	tc := oauth2.NewClient(context.Background(), ts)
	return &Client{
		gh:    gh.NewClient(tc),
		owner: owner,
	}
}

// CreateRepo creates a new GitHub repository and pushes all generated files.
// Returns the HTML URL of the created repo.
func (c *Client) CreateRepo(ctx context.Context, slug string, files []generator.GeneratedFile) (string, error) {
	private := false
	repo, _, err := c.gh.Repositories.Create(ctx, "", &gh.Repository{
		Name:        gh.String(slug),
		Description: gh.String(fmt.Sprintf("Generated by kuberLaunch — %s service", slug)),
		Private:     &private,
		AutoInit:    gh.Bool(true), // creates initial commit so blob API works
	})
	if err != nil {
		return "", fmt.Errorf("create repo: %w", err)
	}

	if err := c.pushFiles(ctx, slug, files); err != nil {
		return *repo.HTMLURL, fmt.Errorf("push files: %w", err)
	}

	return *repo.HTMLURL, nil
}

// pushFiles commits all generated files to the repo in a single commit
// using the Git Tree API. Assumes repo was created with AutoInit=true.
func (c *Client) pushFiles(ctx context.Context, repo string, files []generator.GeneratedFile) error {
	// Get the latest commit SHA on main — empty repo won't have this ref
	ref, _, err := c.gh.Git.GetRef(ctx, c.owner, repo, "refs/heads/main")
	if err != nil {
		// Empty repo: ใช้ Contents API (รองรับ repo ที่ยังไม่มี commit)
		return c.pushFilesViaContents(ctx, repo, files)
	}
	parentSHA := ref.Object.GetSHA()

	// Create blobs for each file
	var treeEntries []*gh.TreeEntry
	for _, f := range files {
		blob, _, err := c.gh.Git.CreateBlob(ctx, c.owner, repo, &gh.Blob{
			Content:  gh.String(f.Content),
			Encoding: gh.String("utf-8"),
		})
		if err != nil {
			return fmt.Errorf("create blob %s: %w", f.Path, err)
		}
		mode := "100644"
		typ := "blob"
		treeEntries = append(treeEntries, &gh.TreeEntry{
			Path: gh.String(f.Path),
			Mode: &mode,
			Type: &typ,
			SHA:  blob.SHA,
		})
	}

	tree, _, err := c.gh.Git.CreateTree(ctx, c.owner, repo, "", treeEntries)
	if err != nil {
		return fmt.Errorf("create tree: %w", err)
	}

	commit, _, err := c.gh.Git.CreateCommit(ctx, c.owner, repo, &gh.Commit{
		Message: gh.String("chore: initial project scaffold by kuberLaunch"),
		Tree:    tree,
		Parents: []*gh.Commit{{SHA: gh.String(parentSHA)}},
	}, &gh.CreateCommitOptions{})
	if err != nil {
		return fmt.Errorf("create commit: %w", err)
	}

	force := true
	_, _, err = c.gh.Git.UpdateRef(ctx, c.owner, repo, &gh.Reference{
		Ref:    gh.String("refs/heads/main"),
		Object: &gh.GitObject{SHA: commit.SHA},
	}, force)
	return err
}

// pushFilesViaContents pushes files one-by-one using the Contents API.
// Used for empty repos where the Git Trees API is unavailable.
func (c *Client) pushFilesViaContents(ctx context.Context, repo string, files []generator.GeneratedFile) error {
	for _, f := range files {
		_, _, err := c.gh.Repositories.CreateFile(ctx, c.owner, repo, f.Path, &gh.RepositoryContentFileOptions{
			Message: gh.String("chore: initial project scaffold by kuberLaunch"),
			Content: []byte(f.Content),
		})
		if err != nil {
			return fmt.Errorf("create file %s: %w", f.Path, err)
		}
	}
	return nil
}

func (c *Client) Owner() string { return c.owner }

// PushFiles pushes all generated files to an existing repo as a new commit.
func (c *Client) PushFiles(ctx context.Context, slug string, files []generator.GeneratedFile) error {
	return c.pushFiles(ctx, slug, files)
}

// RepoExists returns true if the repo already exists under the owner.
func (c *Client) RepoExists(ctx context.Context, slug string) bool {
	_, resp, _ := c.gh.Repositories.Get(ctx, c.owner, slug)
	return resp != nil && resp.StatusCode == 200
}

// TriggerWorkflow dispatches a workflow_dispatch event for the CI workflow.
// Returns the run ID of the triggered workflow run.
func (c *Client) TriggerWorkflow(ctx context.Context, slug, branch string) error {
	_, err := c.gh.Actions.CreateWorkflowDispatchEventByFileName(
		ctx, c.owner, slug, "ci.yml",
		gh.CreateWorkflowDispatchEventRequest{Ref: branch},
	)
	return err
}

// GetLatestWorkflowRun returns the most recent run ID and conclusion for the CI workflow.
// conclusion is empty if the run is still in progress.
func (c *Client) GetLatestWorkflowRun(ctx context.Context, slug string) (runID int64, status, conclusion string, err error) {
	runs, _, err := c.gh.Actions.ListWorkflowRunsByFileName(
		ctx, c.owner, slug, "ci.yml",
		&gh.ListWorkflowRunsOptions{ListOptions: gh.ListOptions{PerPage: 1}},
	)
	if err != nil {
		return 0, "", "", err
	}
	if runs.GetTotalCount() == 0 {
		return 0, "", "", nil
	}
	r := runs.WorkflowRuns[0]
	return r.GetID(), r.GetStatus(), r.GetConclusion(), nil
}

// GetFileContent returns the decoded content of a file in the repo.
func (c *Client) GetFileContent(ctx context.Context, slug, path string) (string, error) {
	file, _, _, err := c.gh.Repositories.GetContents(ctx, c.owner, slug, path, nil)
	if err != nil {
		return "", fmt.Errorf("get file content: %w", err)
	}
	content, err := file.GetContent()
	if err != nil {
		return "", fmt.Errorf("decode file content: %w", err)
	}
	return content, nil
}

// DeleteRepo deletes a GitHub repository.
func (c *Client) DeleteRepo(ctx context.Context, slug string) error {
	_, err := c.gh.Repositories.Delete(ctx, c.owner, slug)
	return err
}

// UpdateFile updates a single file in the repo via the Contents API.
func (c *Client) UpdateFile(ctx context.Context, slug, path, content, message string) error {
	// Get current file SHA (needed for updates)
	file, _, _, err := c.gh.Repositories.GetContents(ctx, c.owner, slug, path, nil)
	if err != nil {
		return fmt.Errorf("get file sha: %w", err)
	}

	_, _, err = c.gh.Repositories.UpdateFile(ctx, c.owner, slug, path, &gh.RepositoryContentFileOptions{
		Message: gh.String(message),
		Content: []byte(content),
		SHA:     file.SHA,
	})
	return err
}
