package github

import (
	"context"
	"encoding/base64"
	"fmt"

	gh "github.com/google/go-github/v66/github"
	"github.com/jakkayy/kuberlauncher/api/internal/generator"
	"golang.org/x/oauth2"
)

type Client struct {
	gh    *gh.Client
	owner string
}

func New(token, owner string) *Client {
	ts := oauth2.StaticTokenSource(&oauth2.Token{AccessToken: token})
	tc := oauth2.NewClient(context.Background(), ts)
	return &Client{
		gh:    gh.NewClient(tc),
		owner: owner,
	}
}

// CreateRepo creates a new GitHub repository and pushes all generated files.
// Returns the HTML URL of the created repo.
func (c *Client) CreateRepo(ctx context.Context, slug string, files []generator.GeneratedFile) (string, error) {
	private := false
	repo, _, err := c.gh.Repositories.Create(ctx, "", &gh.Repository{
		Name:        gh.String(slug),
		Description: gh.String(fmt.Sprintf("Generated by kuberLaunch — %s service", slug)),
		Private:     &private,
		AutoInit:    gh.Bool(true), // creates initial commit so blob API works
	})
	if err != nil {
		return "", fmt.Errorf("create repo: %w", err)
	}

	if err := c.pushFiles(ctx, slug, files); err != nil {
		return *repo.HTMLURL, fmt.Errorf("push files: %w", err)
	}

	return *repo.HTMLURL, nil
}

// pushFiles commits all generated files to the repo in a single commit
// using the Git Tree API. Assumes repo was created with AutoInit=true.
func (c *Client) pushFiles(ctx context.Context, repo string, files []generator.GeneratedFile) error {
	// Get the latest commit SHA on main (created by AutoInit)
	ref, _, err := c.gh.Git.GetRef(ctx, c.owner, repo, "refs/heads/main")
	if err != nil {
		return fmt.Errorf("get ref: %w", err)
	}
	parentSHA := ref.Object.GetSHA()

	// Create blobs for each file
	var treeEntries []*gh.TreeEntry
	for _, f := range files {
		content := base64.StdEncoding.EncodeToString([]byte(f.Content))
		blob, _, err := c.gh.Git.CreateBlob(ctx, c.owner, repo, &gh.Blob{
			Content:  gh.String(content),
			Encoding: gh.String("base64"),
		})
		if err != nil {
			return fmt.Errorf("create blob %s: %w", f.Path, err)
		}
		mode := "100644"
		typ := "blob"
		treeEntries = append(treeEntries, &gh.TreeEntry{
			Path: gh.String(f.Path),
			Mode: &mode,
			Type: &typ,
			SHA:  blob.SHA,
		})
	}

	// Create tree on top of existing tree
	tree, _, err := c.gh.Git.CreateTree(ctx, c.owner, repo, "", treeEntries)
	if err != nil {
		return fmt.Errorf("create tree: %w", err)
	}

	// Create commit with parent (the AutoInit commit)
	parentCommit := &gh.Commit{SHA: gh.String(parentSHA)}
	commit, _, err := c.gh.Git.CreateCommit(ctx, c.owner, repo, &gh.Commit{
		Message: gh.String("chore: initial project scaffold by kuberLaunch"),
		Tree:    tree,
		Parents: []*gh.Commit{parentCommit},
	}, &gh.CreateCommitOptions{})
	if err != nil {
		return fmt.Errorf("create commit: %w", err)
	}

	// Update main branch to point to new commit
	force := true
	_, _, err = c.gh.Git.UpdateRef(ctx, c.owner, repo, &gh.Reference{
		Ref:    gh.String("refs/heads/main"),
		Object: &gh.GitObject{SHA: commit.SHA},
	}, force)
	return err
}

// RepoExists returns true if the repo already exists under the owner.
func (c *Client) RepoExists(ctx context.Context, slug string) bool {
	_, resp, _ := c.gh.Repositories.Get(ctx, c.owner, slug)
	return resp != nil && resp.StatusCode == 200
}
